---
name: Setup Go project
description: Install Go and Task, then prepare project dependencies.
runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6
      with:
        go-version-file: go.mod
        cache: true
    - name: Setup Task
      uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa  # v2
